### PR TITLE
Add d3-rails version 2.9.1

### PR DESCRIPTION
**Pull request by ebouchut**

### CODE REVIEW

**Comment by iblue** [comment]
Merged into tag v2.9.1.

**Comment by ebouchut** [comment]
Thank you.

**Comment by ebouchut** [comment]
Could you push d3-rails version 2.9.1 to rubygems.
Thanks.

**Comment by iblue** [comment]
Ok, done.

2015-02-12 10:29 GMT+01:00 Eric Bouchut <notifications@github.com>:

**Pull request closed without merging**
