### PR TITLE
Update d3 version to v4.2.5

### PR DESCRIPTION
**Pull request by andyyou**

### CODE REVIEW

**Comment by iblue** [comment]
Thanks for your PR. Could you also update the readme, the changelog and `lib/d3/rails/version.rb`?

**Comment by andyyou** [comment]
Sorry I forgot and it fixed now

**Comment by iblue** [comment]
Thank you. Could you also change the `README.md`? It still says 4.2.4.

**Comment by andyyou** [comment]
Fine 😭

**Comment by iblue** [comment]
Awesome, thank you! I just released the new version.

**Pull request merged**
